language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
script:
  - npm test
  - npm run semantic-release-pre
  - npm run build:prod
after_success:
  - npm run publish-npm
  - npm run semantic-release-post
#  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
