language: node_js
dist: trusty
sudo: false
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
addons:
  chrome: stable
install:
  - npm install
script:
  - npm run karma
  - npm run coverage
  - npm run build:prod
