dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm karma
  - npm coverage
  - npm run build:prod
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
