language: node_js
dist: trusty
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
addons:
  chrome: stable
install:
  - yarn
script:
  - yarn karma
  - yarn coverage
  - yarn build:prod
